# Generated by Django 3.2.14 on 2022-08-16 19:18

from django.db import migrations, models

import ppa.archive.models


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0017_digitizedwork_uniquetogether_sourceid_pagerange"),
    ]

    operations = [
        migrations.AddField(
            model_name="digitizedwork",
            name="group_id",
            field=models.CharField(
                blank=True,
                help_text="Identifier for grouping reprints/editions",
                max_length=255,
                verbose_name="Group ID",
            ),
        ),
        migrations.AlterField(
            model_name="digitizedwork",
            name="pages_digital",
            field=models.CharField(
                blank=True,
                help_text="Sequence of pages in the digital edition. Use full digits for start and end separated by a dash (##-##); for multiple sequences, separate ranges by a comma (##-##, ##-##). NOTE: removing page range may have unexpected results.",
                max_length=255,
                validators=[ppa.archive.models.validate_page_range],
                verbose_name="Page range (digital edition)",
            ),
        ),
    ]
